# UDITGUPTA_102203835

##### Importing Numpy

In [1]:
import numpy as np

###### 1(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])  

In [2]:
arr = np.array([1,2,3,4,5])
rev = arr[::-1]
flip = np.flip(arr)
print(rev)
print(flip)

[5 4 3 2 1]
[5 4 3 2 1]


##### 1(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two  NumPy in-built methods 

In [3]:
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat = arr.flatten()
print(flat)
flat2 = arr.ravel()
print(flat2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


#####  1(c) Compare the following numpy arrays:  
##### arr1 = np.array([[1, 2], [3, 4]]) 
##### arr2 = np.array([[1, 2], [3, 4]]) 

In [4]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
print(np.array_equal(arr1,arr2))

True


##### 1(d) Find the most frequent value and their indice(s) in the following arrays: 
##### i. x = np.array([1,2,3,4,5,1,2,1,1,1])  
##### ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])  


In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_x = np.bincount(x).argmax()
ind_x = np.where(x == most_freq_x)
most_freq_y = np.bincount(y).argmax()
ind_y = np.where(y == most_freq_y)
print(f'Most Frequent in X: {most_freq_x}, Indices: {ind_x}')
print(f'Most Frequent in Y: {most_freq_y}, Indices: {ind_y}')

Most Frequent in X: 1, Indices: (array([0, 5, 7, 8, 9], dtype=int64),)
Most Frequent in Y: 1, Indices: (array([0, 1, 2], dtype=int64),)


#####  1(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find  
##### i. Sum of all elements  
##### ii. Sum of all elements row-wise  
##### iii. Sum of all elements column-wise  

In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum = gfg.sum()
row = gfg.sum(axis = 0)
col = gfg.sum(axis = 1)
print(f'SUM : {sum}')
print(f'ROW SUM : {row}')
print(f'COL SUM : \n{col}')

SUM : 45
ROW SUM : [[20  9 16]]
COL SUM : 
[[14]
 [16]
 [15]]


##### 1(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
##### i. Sum of diagonal elements  
##### ii. Eigen values of matrix  
##### iii. Eigen vectors of matrix  
##### 1iv. Inverse of matrix  
##### v. Determinant of matrix 

In [7]:
arr1 = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
dia_sum = np.trace(arr1)
eigen_val,eigen_vector = np.linalg.eig(arr1)
inverse = np.linalg.inv(arr1)
det = np.linalg.det(arr1)
print(dia_sum)
print(eigen_val)
print(eigen_vector)
print(det)
print(inverse)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
137180.0000000001
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


##### 1(g)  Multiply the following matrices and also find covariance between matrices using NumPy: 
##### i. p = [[1, 2], [2, 3]]    q = [[4, 5], [6, 7]]  
##### ii. p = [[1, 2], [2, 3], [4, 5]]    q = [[4, 5, 1], [6, 7, 2]] 


In [8]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
mul1 = np.dot(p,q)
print(mul1)
p1 = p.flatten()
q1 = q.flatten()
cov = np.cov(p1,q1)
print(cov)
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
mul2 = np.dot(p2,q2)
print(mul2)
p3 = p2.flatten()
q3 = q2.flatten()
cov1 = np.cov(p3,q3)
print(cov1)

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


##### 1(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),  find inner, outer and cartesian product? 

In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f'INNER PRODUCT : \n{np.inner(x,y)}')
print(f'OUTER PRODUCT : \n{np.outer(x,y)}')
cart = np.array(np.meshgrid(x,y)).T.reshape(-1,2)
print(f'CARTESIAN PRODUCT : \n{cart}')

INNER PRODUCT : 
[[17 52]
 [13 62]]
OUTER PRODUCT : 
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
CARTESIAN PRODUCT : 
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


##### 2(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
##### i. Find element-wise absolute value  
##### ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each  row.  
##### iii. Mean, Median and Standard Deviation of flattened array, of each column, and  each row  


In [10]:
arr = np.array([[1, -2, 3],[-4, 5, -6]])
absVal = np.abs(arr)
per25 = np.percentile(arr.flatten(),25)
per50 = np.percentile(arr.flatten(),50)
per75 = np.percentile(arr.flatten(),75)
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)
print(absVal)
print(per25,per50,per75)
print(mean_val,median_val,std_val)

[[1 2 3]
 [4 5 6]]
-3.5 -0.5 2.5
-0.5 -0.5 3.8622100754188224


##### 2(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling  and truncated value, rounded values


In [11]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


##### 3(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find  
##### i. Sorted array  
##### ii. Indices of sorted array  
##### iii. 4 smallest elements  
##### iv. 5 largest elements  


In [12]:
arr = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(arr))
print(np.argsort(arr))
print(np.sort(arr)[:4])
print(np.sort(arr)[-5:])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


#####  3(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find  
#####  i. Integer elements only  
#####  ii. Float elements only

In [13]:
arr = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = arr[arr == arr.astype(int)]
floatEle = arr[arr != arr.astype(int)]
print(integers)
print(floatEle)

[1. 2. 3. 2.]
[1.2 2.2]


##### 4(a) Write a function named img_to_array(path) that reads an image from a specified path and  save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale  images)  

In [14]:
import cv2
def img_to_array(path):
    img = cv2.imread(path)
    if len(img.shape) == 3:  # RGB image
        np.savetxt('image_rgb.txt', img.reshape(-1, img.shape[2]), fmt='%d')
    else:  # Grayscale image
        np.savetxt('image_greyscale.txt', img, fmt='%d')
img_to_array(r"C:\Users\udit0\OneDrive\Desktop\ML\Assignments\Assignment 1\Screenshot 2024-08-07 124154.png")

RGB image array has been saved to RGB_image_array.npy


##### 4(b) Load the saved file into jupyter notebook? 

In [15]:
loaded_array = np.load("RGB_image_array.npy")
print("SHAPE OF THE LOADED ARRAY : ",loaded_array.shape)
print("FIRST FEW ELEMENTS OF THE ARRAY : \n",loaded_array[:25])

SHAPE OF THE LOADED ARRAY :  (774390, 3)
FIRST FEW ELEMENTS OF THE ARRAY : 
 [[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
